= More Information

Asynchronicity is an important part of any non-trivial user-facing application. Managing this behavior in a clear, intuitive and effective way is paramount. This is there are so many libraries and new language features that address this issue.

Promises are the foundation of most of the activity, as it provides an object representation of an asynchronous action - this is a crucial step in building more types of programatic flow including asynchronous activities.

Some of the "up and coming" JavaScript features such as generators, yield, async & await are supposed to simplify working with promises and asynchronicity, but:

. They aren't here yet - unless you want to transpile
. I'm not convinced they are the best solutions for most of the challenges we face.

Many of these new language features seem aimed at hiding the asynchronous nature of an activity. I would rather make it clearly asynchronous, yet intuitive to reason about.

== Promisification

In the 1.x.x versions of Zousan-plus I was replacing callback functions with promisified versions of those functions. I ran into issues with some node modules that seemed to be due to internal function calls that didn't play well with my replaced versions.

After the 2.x.x changes in which promisified functions are _added_ to the module with a different name, these issues seem to be curtailed.  Though I am keeping an eye on it.

== 3.0.0

=== eval -> evaluate

ES6 forbids the use of eval as a function name - so it has been changed to evaluate.
