= More Information

Asynchronicity is an important part of any non-trivial user-facing application. Managing this behavior in a clear, intuitive and effective way is paramount.

Promises are the foundation of most of the tooling surrounding asynchronicity, as it provides an object representation of an asynchronous action. This is a crucial step in building more types of programatic flow involving asynchronous activities.

But as useful as some of the newer language features, such as `async` and `await` are, they do not address all of the needs of modern application development.

*Zousan-Plus* was designed to be the "tool-belt" providing the additional necessary asynchronous tools one needs to effortlessly and efficiently handle these needs.

== Promisification

In the 1.x.x versions of Zousan-plus I was replacing callback functions with promisified versions of those functions. I ran into issues with some node modules that seemed to be due to internal function calls that didn't play well with my replaced versions.

After the 2.x.x changes in which promisified functions are _added_ to the module with a different name, these issues seem to be curtailed.  Though I am keeping an eye on it.

== 3.0.0

=== eval -> evaluate

ES6 forbids the use of eval as a function name - so it has been changed to evaluate.

== 4.0.0

*zousan-plus* can now be imported as an ES Module.

For example:

	import Zousan from "../extModules/zousan-plus"

